### ISSUE TITLE
When i pull data ("coronavirus") only brings 1497 cases

### ISSUE THREAD

**Issue by AGSCL** [RamiKrispin/coronavirus#17]
Hello, 

I'm from Chile, and I noticed that when I run `library(coronavirus);data("coronavirus")` even in the devtools version, I don't get information from Chile, but only from Australia, Belgium, Cambodia, Canada, Egypt, Finland, France, Germany, Hong Kong, India, Italy, Japan, Macau, Mainland China, Malaysia, etc., and until February 16 of 2020.

**Comment by RamiKrispin** [comment]
Hi @AGSCL,

Currently, the package Dev version is updated up to March 13th, 2020. You probably are using the CRNA version, try to install from Github using the following:
```
# install.packages("devtools") 
devtools::install_github("RamiKrispin/coronavirus")
```

**Comment by streamblade** [comment]
Similar query: running the data today from your dev version as you suggest above, the US cases are 15 confirmed. In New York State alone it's 1708 as of today. It looks like the most recent date is 2/16/2020. 

I'll assume this package is meant for say monthly retrospective analysis rather than daily updates; fair?

Btw, thx for thinking of creating this package.
